### ISSUE TITLE
Update DSC NIT Rourkela

### ISSUE THREAD

**Issue by DesignrKnight** [dsc-x/dsc-x.github.io#2]
- Add Cover
- Add Display Picture
- Add LinkedIn
- Add Social Media of Chapter

**Comment by DesignrKnight** [comment]
Assigned to @DesignrKnight

**Comment by DesignrKnight** [comment]
Wow, here I am after months, realizing I had not fixed this

**Comment by DesignrKnight** [comment]
Fix at #38

**Comment by aravindvnair99** [comment]
@DesignrKnight You may close this issue as it's merged.
